# Generated by Django 5.0.7 on 2024-08-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_module', '0002_alter_brand_country_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='screem_size',
            new_name='screen_size',
        ),
    ]
