# Generated by Django 5.0.7 on 2024-08-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_module', '0003_rename_screem_size_mobile_screen_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='available',
            new_name='is_available',
        ),
    ]
