# Generated by Django 5.0.7 on 2024-08-04 12:08

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_module', '0004_rename_available_mobile_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='country',
            field=django_countries.fields.CountryField(db_index=True, max_length=2),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='warehouse_m_name_87288b_idx'),
        ),
    ]
