# Generated by Django 5.0.7 on 2024-08-04 12:09

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_module', '0005_alter_mobile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=django_countries.fields.CountryField(db_index=True, max_length=2),
        ),
    ]
