# Generated by Django 5.0.7 on 2024-08-04 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_module', '0007_alter_mobile_screen_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='screen_size',
            field=models.DecimalField(decimal_places=1, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
